// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: ids_proto/ids.proto

package backend_ids

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudentCRUDClient is the client API for StudentCRUD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentCRUDClient interface {
	CreateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Status, error)
	CreateComment(ctx context.Context, in *SolId, opts ...grpc.CallOption) (*Comment, error)
	CreateSolution(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Status, error)
}

type studentCRUDClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentCRUDClient(cc grpc.ClientConnInterface) StudentCRUDClient {
	return &studentCRUDClient{cc}
}

func (c *studentCRUDClient) CreateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.StudentCRUD/CreateQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentCRUDClient) CreateComment(ctx context.Context, in *SolId, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/ids_proto.StudentCRUD/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentCRUDClient) CreateSolution(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.StudentCRUD/CreateSolution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentCRUDServer is the server API for StudentCRUD service.
// All implementations must embed UnimplementedStudentCRUDServer
// for forward compatibility
type StudentCRUDServer interface {
	CreateQuestion(context.Context, *Question) (*Status, error)
	CreateComment(context.Context, *SolId) (*Comment, error)
	CreateSolution(context.Context, *Solution) (*Status, error)
	mustEmbedUnimplementedStudentCRUDServer()
}

// UnimplementedStudentCRUDServer must be embedded to have forward compatible implementations.
type UnimplementedStudentCRUDServer struct {
}

func (UnimplementedStudentCRUDServer) CreateQuestion(context.Context, *Question) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuestion not implemented")
}
func (UnimplementedStudentCRUDServer) CreateComment(context.Context, *SolId) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedStudentCRUDServer) CreateSolution(context.Context, *Solution) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSolution not implemented")
}
func (UnimplementedStudentCRUDServer) mustEmbedUnimplementedStudentCRUDServer() {}

// UnsafeStudentCRUDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentCRUDServer will
// result in compilation errors.
type UnsafeStudentCRUDServer interface {
	mustEmbedUnimplementedStudentCRUDServer()
}

func RegisterStudentCRUDServer(s grpc.ServiceRegistrar, srv StudentCRUDServer) {
	s.RegisterService(&StudentCRUD_ServiceDesc, srv)
}

func _StudentCRUD_CreateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Question)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentCRUDServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.StudentCRUD/CreateQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentCRUDServer).CreateQuestion(ctx, req.(*Question))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentCRUD_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentCRUDServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.StudentCRUD/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentCRUDServer).CreateComment(ctx, req.(*SolId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentCRUD_CreateSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentCRUDServer).CreateSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.StudentCRUD/CreateSolution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentCRUDServer).CreateSolution(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentCRUD_ServiceDesc is the grpc.ServiceDesc for StudentCRUD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentCRUD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ids_proto.StudentCRUD",
	HandlerType: (*StudentCRUDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuestion",
			Handler:    _StudentCRUD_CreateQuestion_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _StudentCRUD_CreateComment_Handler,
		},
		{
			MethodName: "CreateSolution",
			Handler:    _StudentCRUD_CreateSolution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ids_proto/ids.proto",
}
