// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: ids_proto/ids.proto

package backend_ids

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdsCRUDClient is the client API for IdsCRUD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdsCRUDClient interface {
	CreateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Status, error)
	CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Status, error)
	CreateSolution(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Status, error)
	UpdateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Status, error)
	DeleteQuestion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Status, error)
	UpdateSolution(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Status, error)
	DeleteSolution(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Status, error)
}

type idsCRUDClient struct {
	cc grpc.ClientConnInterface
}

func NewIdsCRUDClient(cc grpc.ClientConnInterface) IdsCRUDClient {
	return &idsCRUDClient{cc}
}

func (c *idsCRUDClient) CreateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.idsCRUD/CreateQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idsCRUDClient) CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.idsCRUD/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idsCRUDClient) CreateSolution(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.idsCRUD/CreateSolution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idsCRUDClient) UpdateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.idsCRUD/UpdateQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idsCRUDClient) DeleteQuestion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.idsCRUD/DeleteQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idsCRUDClient) UpdateSolution(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.idsCRUD/UpdateSolution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idsCRUDClient) DeleteSolution(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/ids_proto.idsCRUD/DeleteSolution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdsCRUDServer is the server API for IdsCRUD service.
// All implementations must embed UnimplementedIdsCRUDServer
// for forward compatibility
type IdsCRUDServer interface {
	CreateQuestion(context.Context, *Question) (*Status, error)
	CreateComment(context.Context, *Comment) (*Status, error)
	CreateSolution(context.Context, *Solution) (*Status, error)
	UpdateQuestion(context.Context, *Question) (*Status, error)
	DeleteQuestion(context.Context, *Id) (*Status, error)
	UpdateSolution(context.Context, *Solution) (*Status, error)
	DeleteSolution(context.Context, *Id) (*Status, error)
	mustEmbedUnimplementedIdsCRUDServer()
}

// UnimplementedIdsCRUDServer must be embedded to have forward compatible implementations.
type UnimplementedIdsCRUDServer struct {
}

func (UnimplementedIdsCRUDServer) CreateQuestion(context.Context, *Question) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuestion not implemented")
}
func (UnimplementedIdsCRUDServer) CreateComment(context.Context, *Comment) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedIdsCRUDServer) CreateSolution(context.Context, *Solution) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSolution not implemented")
}
func (UnimplementedIdsCRUDServer) UpdateQuestion(context.Context, *Question) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuestion not implemented")
}
func (UnimplementedIdsCRUDServer) DeleteQuestion(context.Context, *Id) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuestion not implemented")
}
func (UnimplementedIdsCRUDServer) UpdateSolution(context.Context, *Solution) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSolution not implemented")
}
func (UnimplementedIdsCRUDServer) DeleteSolution(context.Context, *Id) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSolution not implemented")
}
func (UnimplementedIdsCRUDServer) mustEmbedUnimplementedIdsCRUDServer() {}

// UnsafeIdsCRUDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdsCRUDServer will
// result in compilation errors.
type UnsafeIdsCRUDServer interface {
	mustEmbedUnimplementedIdsCRUDServer()
}

func RegisterIdsCRUDServer(s grpc.ServiceRegistrar, srv IdsCRUDServer) {
	s.RegisterService(&IdsCRUD_ServiceDesc, srv)
}

func _IdsCRUD_CreateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Question)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsCRUDServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.idsCRUD/CreateQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsCRUDServer).CreateQuestion(ctx, req.(*Question))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdsCRUD_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsCRUDServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.idsCRUD/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsCRUDServer).CreateComment(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdsCRUD_CreateSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsCRUDServer).CreateSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.idsCRUD/CreateSolution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsCRUDServer).CreateSolution(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdsCRUD_UpdateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Question)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsCRUDServer).UpdateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.idsCRUD/UpdateQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsCRUDServer).UpdateQuestion(ctx, req.(*Question))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdsCRUD_DeleteQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsCRUDServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.idsCRUD/DeleteQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsCRUDServer).DeleteQuestion(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdsCRUD_UpdateSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsCRUDServer).UpdateSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.idsCRUD/UpdateSolution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsCRUDServer).UpdateSolution(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdsCRUD_DeleteSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsCRUDServer).DeleteSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ids_proto.idsCRUD/DeleteSolution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsCRUDServer).DeleteSolution(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// IdsCRUD_ServiceDesc is the grpc.ServiceDesc for IdsCRUD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdsCRUD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ids_proto.idsCRUD",
	HandlerType: (*IdsCRUDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuestion",
			Handler:    _IdsCRUD_CreateQuestion_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _IdsCRUD_CreateComment_Handler,
		},
		{
			MethodName: "CreateSolution",
			Handler:    _IdsCRUD_CreateSolution_Handler,
		},
		{
			MethodName: "UpdateQuestion",
			Handler:    _IdsCRUD_UpdateQuestion_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _IdsCRUD_DeleteQuestion_Handler,
		},
		{
			MethodName: "UpdateSolution",
			Handler:    _IdsCRUD_UpdateSolution_Handler,
		},
		{
			MethodName: "DeleteSolution",
			Handler:    _IdsCRUD_DeleteSolution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ids_proto/ids.proto",
}
